repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
    - id: mixed-line-ending
      args: ['--fix=lf']

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-black
          - mdformat-myst

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      name: Checks for common misspellings in text files.

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
    - id: isort
      name: Sort imports with isort

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    - id: black
      name: Autoformat with black
      args: [-t, py311, -l, "100"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
    - id: pyupgrade
      name: Upgrade synax to python 3.11+ with pyupgrade
      args: [--py311-plus]
