name: Build and Update README

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0
        path: main

    - name: Checkout til-db
      uses: actions/checkout@v4
      with:
        repository: cheginit/til-db
        path: til-db
        token: ${{ secrets.DB_PUSH }}

    - name: Create a Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        pip install -r main/requirements.txt

    - name: Build database
      run: |-
        cd main
        python build_database.py

    - name: Update README
      run: |-
        cd main
        python update_readme.py --rewrite
        cat README.md

    - name: Commit and push if READMEs changed
      run: |-
        cd main
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git status -sb README.md */README.md
        N_CHANGES=$(git status --porcelain=v1 README.md */README.md 2>/dev/null | wc -l)
        if [[ $N_CHANGES -gt 0 ]]; then
          git add README.md */README.md
          git commit -m "GHW: Updated READMEs [skip ci]"
          git push
        fi

    - name: Save tils.db to cheginit/til-db
      run: |-
        cd til-db
        cp ../main/tils.db .
        git add tils.db
        git commit --amend --no-edit
        git push --force
